### PR TITLE
Add Documentation for Virtual Assistance for blind people

### PR DESCRIPTION
**Pull request by gaurav0github**

### CODE REVIEW

**Comment by Nageshbansal** [comment]
Hi @gaurav0github,
Thank you for the PR.
I would suggest that you make changes in a single PR only. You can add the changes to PR #1 .

**Comment by VasuKashiv** [comment]
@Nageshbansal code and readme files have been updated in this #2 PR
You may merge it.
Thank You

**Comment by ph1ne4s** [comment]
Need installation procedure in the readme file.

**Review by Shinchan9913 — CHANGES_REQUESTED** [review]
@VasuKashiv setup instructions missing

**Review by ph1ne4s — APPROVED** [review]

**Review by Nageshbansal — CHANGES_REQUESTED** [review]
Please do the required changes asap

**Comment by gaurav0github** [comment]
> Please do the required changes asap

Done

**Comment by ph1ne4s** [comment]
@Nageshbansal this PR is ready to merge.

**Review by Nageshbansal — APPROVED** [review]

**Comment by Nageshbansal** [comment]
Good work @gaurav0github @VasuKashiv @deev1010  🚀

**Comment by gaurav0github** [comment]
> Good work @gaurav0github @VasuKashiv @deev1010 🚀

Thanks Sir

**Pull request merged**
